# Blank issues are needded for the link checker action
blank_issues_enabled: false
contact_links:
  - name: Terraform on SAP BTP Landing Page - Community Support
    url: https://github.com/SAP-docs/terraform-landingpage-for-btp
    about: Please ask and answer questions here.
