name: 🚀 Feature Request
description: Suggest an idea or Request a feature for the Terraform on SAP BTP Landing Page
title: "[FEATURE_REQ] <your title comes here>"
labels: ["enhancement", "improvement"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area of the Terraform on SAP BTP Landing Page that should be enhanced?
      options:
        - Where to start?
        - The Terraform Providers
        - In the Bigger Context
        - Terraform Exporter for SAP BTP
        - Terraform Sample Code
        - Webinars and Videos
        - Latest Versions
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Overview of feature request
      description: What are you proposing to be added/updated/removed?
      placeholder: |
        A clear and concise description of what the feature is. Ex. I would like to see [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: What will need to be completed/working for this feature to be marked "Done"?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here
      placeholder: |
        Links? References? Anything that will give us more context about the feature you are looking for!

        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
