name: Test deployment
permissions:
  contents: read

on:
  pull_request:

jobs:
  test-build:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version: 20.x
      - name: Install dependencies
        working-directory: ./content
        run: npm ci
      - name: Test build website
        working-directory: ./content
        run: npm run build
